apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pv-claim
  namespace: wordpress
  labels:
    # type: longhorn
    type: civo-volume
    app: wordpress
spec:
  # storageClassName: longhorn
  storageClassName: civo-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

